# Generated by Django 5.2.8 on 2025-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReinfNFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('access_key', models.CharField(max_length=60, unique=True)),
                ('number', models.CharField(max_length=40)),
                ('competence', models.DateField(blank=True, null=True)),
                ('emission_datetime', models.DateTimeField(blank=True, null=True)),
                ('dps_number', models.CharField(blank=True, max_length=40)),
                ('dps_series', models.CharField(blank=True, max_length=40)),
                ('dps_emission_datetime', models.DateTimeField(blank=True, null=True)),
                ('emitter_name', models.CharField(max_length=255)),
                ('emitter_cnpj', models.CharField(max_length=20)),
                ('emitter_inscription', models.CharField(blank=True, max_length=40)),
                ('emitter_phone', models.CharField(blank=True, max_length=40)),
                ('emitter_email', models.EmailField(blank=True, max_length=254)),
                ('emitter_address', models.CharField(blank=True, max_length=255)),
                ('emitter_zipcode', models.CharField(blank=True, max_length=12)),
                ('emitter_optante_simples', models.BooleanField(default=False)),
                ('emitter_regime_especial', models.CharField(blank=True, max_length=120)),
                ('taker_name', models.CharField(max_length=255)),
                ('taker_cnpj', models.CharField(blank=True, max_length=20)),
                ('taker_phone', models.CharField(blank=True, max_length=40)),
                ('taker_email', models.EmailField(blank=True, max_length=254)),
                ('taker_address', models.CharField(blank=True, max_length=255)),
                ('taker_zipcode', models.CharField(blank=True, max_length=12)),
                ('service_national_code', models.CharField(blank=True, max_length=40)),
                ('service_municipal_code', models.CharField(blank=True, max_length=40)),
                ('service_location', models.CharField(blank=True, max_length=120)),
                ('service_description', models.TextField(blank=True)),
                ('service_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_base_calculo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_iss_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_iss_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_iss_retido', models.BooleanField(default=False)),
                ('municipal_regime', models.CharField(blank=True, max_length=120)),
                ('municipal_incidence_city', models.CharField(blank=True, max_length=120)),
                ('municipal_taxation', models.CharField(blank=True, max_length=120)),
                ('tax_comment', models.TextField(blank=True)),
                ('federal_tax_comment', models.TextField(blank=True)),
                ('totals_service_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totals_iss_retido', models.BooleanField(default=False)),
                ('totals_retained_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totals_net_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('complementary_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NFSe importada',
                'verbose_name_plural': 'NFSe importadas',
                'db_table': 'reinf_NFS',
            },
        ),
    ]
