# Generated by Django 5.2.8 on 2025-11-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse', '0005_alter_importjobfile_stored_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinfnfs',
            name='company_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='reinfnfs',
            name='competence_period',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='importjobfile',
            name='stage',
            field=models.CharField(choices=[('queued', 'Fila'), ('ocr', 'OCR'), ('ai', 'LLM'), ('persisting', 'Persistindo'), ('done', 'Finalizado'), ('error', 'Erro')], default='queued', max_length=20),
        ),
    ]
