# Generated by Django 5.2.8 on 2026-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse', '0007_importjobfile_export_to_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCompany',
            fields=[
                ('cod_folha', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('matriz', models.CharField(blank=True, db_column='Matriz', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Empresa (DP)',
                'verbose_name_plural': 'Empresas (DP)',
                'db_table': 'geral_planilha_gerencial',
                'managed': False,
            },
        ),
    ]
