# Generated by Django 5.2.8 on 2026-02-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_app_lab_946901_idx',
            old_name='auditlog_ap_app_lab_0e10fa_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_actor_i_e7d961_idx',
            old_name='auditlog_ac_actor_i_146147_idx',
        ),
    ]
