"""
Django settings for painel_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')


def env_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY', 'django-insecure-+%198#xe9i0jl%%(9*%r6!0u+ak!2nsv#d!w9z%r&0rn=s-wcy'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool(os.getenv('DJANGO_DEBUG'), True)

allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'nfse',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'painel_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'painel_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_NAME', 'automacoesfiscal_dev'),
        'USER': os.getenv('MYSQL_USER', 'denis'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'hJ3#xL9v!2Zq'),
        'HOST': os.getenv('MYSQL_HOST', '10.0.0.80'),
        'PORT': os.getenv('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'init_command': os.getenv(
                'MYSQL_INIT_COMMAND', "SET sql_mode='STRICT_TRANS_TABLES'"
            ),
        },
    },
    'automacoesdp': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DP_NAME', 'automacoesdp_uat'),
        'USER': os.getenv('MYSQL_DP_USER', os.getenv('MYSQL_USER', 'denis')),
        'PASSWORD': os.getenv('MYSQL_DP_PASSWORD', os.getenv('MYSQL_PASSWORD', 'hJ3#xL9v!2Zq')),
        'HOST': os.getenv('MYSQL_DP_HOST', os.getenv('MYSQL_HOST', '10.0.0.80')),
        'PORT': os.getenv('MYSQL_DP_PORT', os.getenv('MYSQL_PORT', '3306')),
        'OPTIONS': {
            'init_command': os.getenv(
                'MYSQL_DP_INIT_COMMAND', "SET sql_mode='STRICT_TRANS_TABLES'"
            ),
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'welcome'

cors_allowed = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_allowed.split(',') if origin.strip()]
CORS_ALLOW_CREDENTIALS = True

FIREBIRD_CONNECTION = {
    'HOST': os.getenv('FIREBIRD_HOST', 'localhost'),
    'DATABASE': os.getenv('FIREBIRD_DATABASE', '/path/to/firebird/database.fdb'),
    'USER': os.getenv('FIREBIRD_USER', 'sysdba'),
    'PASSWORD': os.getenv('FIREBIRD_PASSWORD', 'masterkey'),
    'PORT': int(os.getenv('FIREBIRD_PORT', '3050')),
}
